export const POSTS_FETCH_REQUEST = 'POSTS_FETCH_REQUEST';
export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
export const POSTS_FETCH_ERROR = 'POSTS_FETCH_ERROR';
export const POST_INC_LIKE = 'POST_INC_LIKE';
