export const POSTS_FETCH_REQUEST = 'POSTS_FETCH_REQUEST';
export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
export const POSTS_FETCH_ERROR = 'POSTS_FETCH_ERROR';
export const POSTS_ADD_TOGGLE = 'POSTS_ADD_TOGGLE';
export const POSTS_ADD_REQUEST = 'POSTS_ADD_REQUEST';
export const POSTS_ADD_SUCCESS = 'POSTS_ADD_SUCCESS';
export const POSTS_ADD_ERROR = 'POSTS_ADD_ERROR';
